baseURL = "https://masa162.github.io/name/"
languageCode = "ja"
title = "（あなたのマンガのタイトルなど）"
theme = "PaperMod"

[params]
  ShowReadingTime = true
  ShowShareButtons = true
  ShowPostNavLinks = true
  ShowBreadCrumbs = true
  ShowCodeCopyButtons = true