baseURL = "https://masa12.github.io/name/"
languageCode = "ja"
title = "blue moon"
theme = "PaperMod"

[params]
    ShowReadingTime = true
    ShowShareButtons = true
    ShowPostNavLinks = true
    ShowBreadCrumbs = true
    ShowCodeCopyButtons = true
    ShowWordCount = true
    ShowRssButtonInSectionTermList = true
    UseHugoToc = true